// <auto-generated />
using System;
using ETI_X_2024_IntroASPNETCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETI_X_2024_IntroASPNETCore.Migrations
{
    [DbContext(typeof(ETI_X_2024_IntroASPNETCoreContext))]
    [Migration("20241008072541_sportInit")]
    partial class sportInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Kategoria", b =>
                {
                    b.Property<int>("KategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriaId"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriaId");

                    b.ToTable("Kategoria");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Kolor", b =>
                {
                    b.Property<int>("KolorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KolorId"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KolorId");

                    b.ToTable("Kolor");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Marka", b =>
                {
                    b.Property<int>("MarkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarkaId"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarkaId");

                    b.ToTable("Marka");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelId");

                    b.ToTable("Model");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Produkt", b =>
                {
                    b.Property<int>("ProduktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduktId"));

                    b.Property<float>("Cena")
                        .HasColumnType("real");

                    b.Property<int?>("KategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProduktId");

                    b.HasIndex("KategoriaId");

                    b.ToTable("Produkt");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.RodzajSilnika", b =>
                {
                    b.Property<int>("RodzajSilnikaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RodzajSilnikaId"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RodzajSilnikaId");

                    b.ToTable("RodzajSilnika");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Samochod", b =>
                {
                    b.Property<int>("SamochodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SamochodId"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int?>("KolorId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkaId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("Przebieg")
                        .HasColumnType("int");

                    b.Property<int?>("RodzajSilnikaId")
                        .HasColumnType("int");

                    b.Property<int>("RokProdukcji")
                        .HasColumnType("int");

                    b.HasKey("SamochodId");

                    b.HasIndex("KolorId");

                    b.HasIndex("MarkaId");

                    b.HasIndex("ModelId");

                    b.HasIndex("RodzajSilnikaId");

                    b.ToTable("Samochod");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportId");

                    b.ToTable("Sport");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Trening", b =>
                {
                    b.Property<int>("TreningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreningId"));

                    b.Property<TimeSpan>("Czas")
                        .HasColumnType("time");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<float>("Dystans")
                        .HasColumnType("real");

                    b.Property<int?>("SportId")
                        .HasColumnType("int");

                    b.Property<int?>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("TreningId");

                    b.HasIndex("SportId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Trening");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Uzytkownik", b =>
                {
                    b.Property<int>("UzytkownikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UzytkownikId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wzrost")
                        .HasColumnType("int");

                    b.HasKey("UzytkownikId");

                    b.ToTable("Uzytkownik");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Waga", b =>
                {
                    b.Property<int>("WagaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WagaId"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<float>("Wartosc")
                        .HasColumnType("real");

                    b.HasKey("WagaId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Waga");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Produkt", b =>
                {
                    b.HasOne("ETI_X_2024_IntroASPNETCore.Models.Kategoria", "Kategoria")
                        .WithMany("Produkts")
                        .HasForeignKey("KategoriaId");

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Samochod", b =>
                {
                    b.HasOne("ETI_X_2024_IntroASPNETCore.Models.Kolor", "Kolor")
                        .WithMany("Samochods")
                        .HasForeignKey("KolorId");

                    b.HasOne("ETI_X_2024_IntroASPNETCore.Models.Marka", "Marka")
                        .WithMany("Samochods")
                        .HasForeignKey("MarkaId");

                    b.HasOne("ETI_X_2024_IntroASPNETCore.Models.Model", "Model")
                        .WithMany("Samochods")
                        .HasForeignKey("ModelId");

                    b.HasOne("ETI_X_2024_IntroASPNETCore.Models.RodzajSilnika", "RodzajSilnika")
                        .WithMany("Samochods")
                        .HasForeignKey("RodzajSilnikaId");

                    b.Navigation("Kolor");

                    b.Navigation("Marka");

                    b.Navigation("Model");

                    b.Navigation("RodzajSilnika");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Trening", b =>
                {
                    b.HasOne("ETI_X_2024_IntroASPNETCore.Models.Sport", "Sport")
                        .WithMany("Trenings")
                        .HasForeignKey("SportId");

                    b.HasOne("ETI_X_2024_IntroASPNETCore.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Trenings")
                        .HasForeignKey("UzytkownikId");

                    b.Navigation("Sport");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Waga", b =>
                {
                    b.HasOne("ETI_X_2024_IntroASPNETCore.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Wagas")
                        .HasForeignKey("UzytkownikId");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Kategoria", b =>
                {
                    b.Navigation("Produkts");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Kolor", b =>
                {
                    b.Navigation("Samochods");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Marka", b =>
                {
                    b.Navigation("Samochods");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Model", b =>
                {
                    b.Navigation("Samochods");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.RodzajSilnika", b =>
                {
                    b.Navigation("Samochods");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Sport", b =>
                {
                    b.Navigation("Trenings");
                });

            modelBuilder.Entity("ETI_X_2024_IntroASPNETCore.Models.Uzytkownik", b =>
                {
                    b.Navigation("Trenings");

                    b.Navigation("Wagas");
                });
#pragma warning restore 612, 618
        }
    }
}
